### ISSUE TITLE
RNO server does not wait for opponents and fail

### ISSUE THREAD

**Issue by jan-burianek** [worldofbalance/wob-server#24]
RNO server does not wait for other opponents so in case there's only one client connected, the code fails in `RequestSpecies` at line 44:

```
p_id = RaceManager.manager.getRaceByPlayerID(client.getPlayer().getID())
                .getOpponent(client.getPlayer()).getID();
```

A way how to reproduce this issue:
1. Start server & one client
2. Login
3. Join Race
4. Run
5. Select species & run

```
Request [111] Error:
null

---
java.lang.NullPointerException
    at networking.request.RequestRRSpecies.doBusiness(RequestRRSpecies.java:57)
    at core.GameClient.run(GameClient.java:136)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Solution would be
1. just wait for anybody else
2. let to know the client that it is waiting

The second point significantly increases the complexity of this issue, so my proposal is just to wait for another guy.

**Comment by laisture** [comment]
@jan-burianek I will look at this issue and try to get it resolved asap. Did you use the development branch?

EDIT: Also which client branch are you using?
